<?php

// WARNING: Do not edit this file. Copy or rename it as config.php before change it

// Default language
define('ADDON_MOODLE_DEFAULT_LANGUAGE', 'en');

// If the matrikelnummer should be synchronized
define('ADDON_MOODLE_SYNC_PERSONENKENNZEICHEN', false);

// If the management staff should be synchronized
define('ADDON_MOODLE_SYNC_FACHBEREICHSLEITUNG', false);

// Roles IDs in moodle
define('ADDON_MOODLE_LEKTOREN_ROLEID', 3);
define('ADDON_MOODLE_STUDENT_ROLEID', 5);
define('ADDON_MOODLE_FACHBEREICHSLEITUNG_ROLEID', 10);

// Enable or disable debug messages
define('ADDON_MOODLE_DEBUG_ENABLED', false);

// Perform a dry run (= do NOT write in moodle or database)
define('ADDON_MOODLE_DRY_RUN', false);

// Connection configuration
$activeConnection = 'DEFAULT'; // the used configuration set of the chosen connection

// Example of a configuration set, all parameters are required!
$connection = array(
	'DEFAULT' => array(
		PROTOCOL => 'https', // ssl by default... better!
	    HOST => 'hostname', // moodle server name
	    PATH => 'webservice/rest/server.php', // usually this is the path for REST API
		TOKEN => '123456', // activated token
		WS_FORMAT => 'json' // default JSON
	)
);
