<?php

// WARNING: Do not edit this file. Copy or rename it as config.php before change it

$debug = false; // if it set as true debug infos will be logged in the apache error log

$activeConnection = 'DEFAULT'; // the used configuration set of the chosen connection

// Example of a configuration set, all parameters are required!
$connection = array(
	'DEFAULT' => array(
		PROTOCOL => 'https', // ssl by default... better!
	    HOST => 'hostname', // moodle server name
	    PATH => 'webservice/rest/server.php', // usually this is the path for REST API
		TOKEN => '123456', // activated token
		WS_FORMAT => 'json' // default JSON
	)
);
